version: "3.3"
services:
  backend-frontend:
    build:
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - BASE_URL=http://instagrapi:8000
    networks:
      - app-network
    volumes:
      - .:/app
  instagrapi:
    build:
      context: https://github.com/adw0rd/instagrapi-rest.git#main
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./packages/server/storage:/app/storage

networks:
  app-network:
    driver: bridge
